### ISSUE TITLE
cant select an option

### ISSUE THREAD

**Issue by UN5T48L3** [GitHackTools/Leaked#1]
when I select any option, It comes nothing. No idea whats the problem.

![ekran resmi 2018-09-03 18 18 20](https://user-images.githubusercontent.com/39417235/44994109-d0a8fb00-afa5-11e8-86ef-b09f0d5a3e79.png)

**Comment by gitkern3l** [comment]
Sorry for late response!
It was written in Python 3 oh man

**Comment by UN5T48L3** [comment]
oh ty so much man. I will try with python3

**Comment by thehappydinoa** [comment]
I will make a PR fix for this:

```python
try:
    input = raw_input
except NameError:
    pass
```

**Comment by gitkern3l** [comment]
Thanks!
